### ISSUE TITLE
Should we switch Minitest to RSpec for the test suite?

### ISSUE THREAD

**Issue by andela-oakinniranye** [coderwall/coderwall-next#40]
Seeing that comprehensive tests has not been written, I was thinking if it makes sense to switch the test suite to RSpec? I believe RSpec is more expressive in describing tests and other contributors would easily understand the intention behind each action/method. I believe this would provide a clearer path for newer contributors.

**Comment by mdeiters** [comment]
We do need a better test suite 😁 

Maybe @seuros wants to chime in here since he made it minitest?

Personally I like lightweight tests (not a lot of magic) with just a few bits syntax sugar like using "its" to define tests instead of method names. Minitest provides that but I'd be ok with rspec too

**Comment by andela-oakinniranye** [comment]
@seuros any thoughts on this?

**Comment by seuros** [comment]
@mdeiters said, Rspec has lot of magic under the hood. 

If you want expressiveness , you can use Minitest Spec Syntax. 

As for contributors, syntax can be acquired in less than 2 h. Minitest don't have many magic matchers like RSpec does.

Also Active Support requires Minitest by default, so we are not adding any dependency here.

**Comment by mdeiters** [comment]
Cool - thanks everyone for chiming in. I think we just keep it simple, no extra dependencies etc. You can still use much of the expressiveness  of  rspec like syntax with minitest too
